name: 02 - Build & Terraform Plan

on:
  workflow_run:
    workflows: ["01 - Quality & Security"]
    types:
      - completed

jobs:
  build-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Package Lambda
        run: |
          npm install
          zip -r terraform/lambda_payload.zip src package.json node_modules

      - uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: terraform/lambda_payload.zip

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}" -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
